AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: E2E Test for aws-sns-to-slack

Parameters:
  StageName:
    Type: String
    Default: test

  NormalKey:
    Type: String
    Default: default

  SpecificKey:
    Type: String
    Default: specific

  LambdaLogGroupNamePrefix:
    Type: String
    Default: /aws/lambda

Resources:
  TmpBucket:
    Type: AWS::S3::Bucket

  API:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName

  DefaultBackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/e2e_backend
      Handler: index.handler
      Runtime: python3.6
      Policies:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Environment:
        Variables:
          S3_BUCKET: !Ref TmpBucket
          S3_KEY: !Ref NormalKey
      Events:
        Normal:
          Type: Api
          Properties:
            RestApiId: !Ref API
            Path: /default
            Method: POST

  DefaultBackendLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub ${LambdaLogGroupNamePrefix}/${DefaultBackendFunction}

  SpecificBackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/e2e_backend
      Handler: index.handler
      Policies:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Runtime: python3.6
      Environment:
        Variables:
          S3_BUCKET: !Ref TmpBucket
          S3_KEY: !Ref SpecificKey
      Events:
        Specific:
          Type: Api
          Properties:
            RestApiId: !Ref API
            Path: /specific
            Method: POST

  SpecificBackendLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub ${LambdaLogGroupNamePrefix}/${SpecificBackendFunction}

  AWSSnsToSlack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DefaultSlackIncommingWebhookUrl: !Sub https://${API}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/default
      TemplateURL: sam.yml

  TestLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonSNSFullAccess
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess

  AnotherNameTopicArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: !GetAtt AWSSnsToSlack.Outputs.SlackNotifierTopicArn

  TestPython36LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.6
      Timeout: 300
      MemorySize: 256
      CodeUri: src/handlers/e2e
      Handler: index.lambda_handler
      Role: !GetAtt TestLambdaRole.Arn
      Layers:
        - !GetAtt AWSSnsToSlack.Outputs.SlackNotifierLayerArn

  TestPython36LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub ${LambdaLogGroupNamePrefix}/${TestPython36LambdaFunction}

  TestPython37LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Timeout: 300
      MemorySize: 256
      CodeUri: src/handlers/e2e
      Handler: index.lambda_handler
      Role: !GetAtt TestLambdaRole.Arn
      Layers:
        - !GetAtt AWSSnsToSlack.Outputs.SlackNotifierLayerArn

  TestPython37LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub ${LambdaLogGroupNamePrefix}/${TestPython37LambdaFunction}

Outputs:
  DefaultUrl:
    Value: !Sub https://${API}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/default
  SpecificUrl:
    Value: !Sub https://${API}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/specific
  SNSTopicArn:
    Value: !GetAtt AWSSnsToSlack.Outputs.SlackNotifierTopicArn
  AnotherNameTopicArnParameterName:
    Value: !Ref AnotherNameTopicArnParameter
  TestPython36LambdaFunctionArn:
    Value: !GetAtt TestPython36LambdaFunction.Arn
  TestPython37LambdaFunctionArn:
    Value: !GetAtt TestPython37LambdaFunction.Arn
  TmpBucketName:
    Value: !Ref TmpBucket
  NormalKey:
    Value: !Ref NormalKey
  SpecificKey:
    Value: !Ref SpecificKey
