version: 2

references:
  base_container: &base_container
    docker:
      - image: circleci/python:3.7
  install_dependencies: &install_dependencies
    run:
      name: pipenv install
      command: pip install pipenv && pipenv install --dev

jobs:
  lint:
    <<: *base_container
    steps:
      - checkout
      - <<: *install_dependencies
      - run:
          name: make lint
          command: make lint
  test-e2e:
    <<: *base_container
    steps:
      - checkout
      - <<: *install_dependencies
      - run:
          name: make test-e2e
          command: make test-e2e

workflows:
  version: 2
  test:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/
      - test-e2e:
          requires:
            - lint
          filters:
            tags:
              only: /.*/
