version: 2

references:
  base_container: &base_container
    docker:
      - image: circleci/python:3.6.8
  install_dependencies: &install_dependencies
    run:
      name: pipenv install
      command: pip install pipenv && pipenv install --dev

jobs:
  lint:
    <<: *base_container
    steps:
      - run:
          name: make lint
          command: env | sort
  test-e2e:
    <<: *base_container
    steps:
      - checkout
      - <<: *install_dependencies
      - run:
          name: make create-e2e-stack
          command: make create-e2e-stack
      - run:
          name: make test-e2e
          command: make test-e2e
      - run:
          name: make delete-e2e-stack
          command: make delete-e2e-stack
          when: always

workflows:
  version: 2
  test:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/
      - test-e2e:
          requires:
            - lint
          filters:
            branches:
              only: master
            tags:
              only: /.*/
